server:
  listen: ":8081"
  read_timeout: "30s"
  write_timeout: "30s"
  shutdown_timeout: "10s"

access_log:
  format: "common"

middlewares:
  - type: rate_limit
    requests: 100
    window: "1m"
    burst: 20
  
  - type: headers
    request:
      add:                        
        X-Forwarded-Service: "reverse-proxy"
      set:                        
        X-Request-Source: "external"
      remove: ["Cookie", "Referer"] 
    response:
      add:
        X-Cache: "HIT"
      set:
        Server: "nginx"
      remove: ["X-Powered-By"]

  - type: cors
    allowed_origins:
      - "http://app.example.com"
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_credentials: true
    exposed_headers: ["X-Total-Count", "X-Page"]

  - type: request_id
  - type: security_headers

routes:
  api.example.com:
    backend: "http://localhost:8080"

  admin.example.com:
    backend: "http://localhost:8080"
    middlewares:
      - type: basic_auth
        users:
          admin: "$2a$10$2fRZfGJvLm7ltnPRBBgmTeue3h3F5UB8B2fRZfGJvLm7ltnPR"
          editor: "$2a$10$8EhVMA3LFwFnKGsFGPmfYuD8c9fNwL5L8nVMA3LFwFnKGsFG"
        realm: "Admin Panel"

